# Configuracion de Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Configuracion de Cache (usar Redis como proveedor de cache)
spring.cache.type=redis
spring.cache.cache-names=transactions
spring.cache.redis.time-to-live=${fraude.cache-minutos}m