# app name
spring.application.name=payment-service
server.port=8080

########## ENDPOINT HEALTH  ###################
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Configuracion
pago.monto-max=500000
fraude.cache-minutos=5

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.fraudProvider.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.fraudProvider.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.fraudProvider.sliding-window-size=5
resilience4j.circuitbreaker.instances.fraudProvider.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.fraudProvider.failureRateThreshold=50
resilience4j.circuitbreaker.instances.fraudProvider.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.fraudProvider.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.fraudProvider.automaticTransitionFromOpenToHalfOpenEnabled=true

# Resilience4j Time Limiter
resilience4j.timelimiter.instances.fraudProvider.timeoutDuration=1s
resilience4j.timelimiter.instances.fraudProvider.cancelRunningFuture=true